export const ACTION_TYPES = {
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENT_DETAILS: 'LOAD_EVENT_DETAILS',
  GET_CURRENT_GEOLOCATION: 'GET_CURRENT_GEOLOCATION',
  GET_MARKERS: 'GET_MARKERS',
  SHOW_MARKER_POPOVER: 'SHOW_MARKER_POPOVER',
  NEW_SEARCH: 'NEW_SEARCH',
  ADD_COMMENT: 'ADD_COMMENT',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  LOAD_RECOMMENDED_EVENTS_SUCCESS: 'LOAD_RECOMMENDED_EVENTS_SUCCESS',
  ADD_EVENT_RATING: 'ADD_EVENT_RATING',
  GET_AVERAGE_RATING: 'GET_AVERAGE_RATING',
};
